use_frameworks!

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end

target 'LTScrollView_Example' do
#    个人项目中使用
#    pod 'LTScrollView'

#   本Demo中使用, LTScrollView不依赖任何第三方框架
    pod 'MJRefresh', '~> 3.1.14.1'

end
